name: contour_plots_env
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - python.app
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - jupyterlab
  - nodejs
  - numpy
  - ipywidgets
